"""DOCKER-USER ruleset script: allow exactly the observed flows, drop the rest.

Container IPs are resolved at *apply* time via ``docker inspect`` so the
script stays correct across container recreations. Rules are written to
Docker's ``DOCKER-USER`` chain (the reserved hook for custom forwarding
policy) and scoped to the app's bridge subnet.
"""

from __future__ import annotations

from pathlib import Path

from app.generators.common import Rule, to_rules

CHAIN = "DOCKER-USER"


def services(rules: list[Rule]) -> list[str]:
    return sorted({name for r in rules for name in (r.src, r.dst)})


def build_script(
    project: str,
    edges,
    *,
    subnet: str = "172.18.0.0/16",
    project_name: str | None = None,
) -> str:
    rules = to_rules(edges)
    names = services(rules)
    project = project_name or project

    body: list[str] = []
    body.append("#!/usr/bin/env bash")
    body.append(f'# Generated by zero-trace for project "{project}"')
    body.append(f"# Least-privilege inter-container firewall via {CHAIN}.")
    body.append(f"# Scope: traffic within the {subnet} bridge subnet.")
    body.append("set -euo pipefail")
    body.append("")
    body.append(f"PROJECT='{project}'")
    body.append(f"CHAIN='{CHAIN}'")
    body.append("")

    # Resolve each service's live container IP at apply time.
    body.append("svc_ip() {")
    body.append("  docker ps --filter label=com.docker.compose.project=$PROJECT \\")
    body.append("             --filter label=com.docker.compose.service=$1 -q | \\")
    body.append("    xargs -r -I{} docker inspect --format \\")
    body.append(
        "      '{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' {} | \\"
    )
    body.append("    awk '{print $1}'")
    body.append("}")
    body.append("")
    for name in names:
        body.append(f"IP_{name.upper()}=$(svc_ip {name})")
    body.append("")

    body.append(f"# --- reset our rules (docker recreates {CHAIN} anyway) ---")
    body.append(f"iptables -F {CHAIN} || true")
    body.append("")
    body.append("# --- allowlist: exactly what was observed ---")
    for r in rules:
        body.append(f"# {r.src} -> {r.dst}  {r.proto}/{r.port}")
        body.append(
            f"iptables -A {CHAIN} -s $IP_{r.src.upper()} -d $IP_{r.dst.upper()} "
            f"-p {r.proto} --dport {r.port} -j ACCEPT"
        )
    body.append("")
    body.append("# default-deny everything else inside the app subnet")
    body.append(f"iptables -A {CHAIN} -s {subnet} -d {subnet} -j DROP")
    body.append(f"iptables -A {CHAIN} -j RETURN")
    body.append("")
    body.append(
        f'echo "zero-trace: hardened firewall applied ({len(rules)} allow rules)."'
    )
    return "\n".join(body) + "\n"


def write(
    project: str,
    edges,
    *,
    out_dir: Path,
    project_name: str | None = None,
) -> Path:
    script = build_script(project, edges, project_name=project_name)
    target = out_dir / "iptables.hardened.sh"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(script, encoding="utf-8")
    target.chmod(0o755)
    return target
