server {
    listen       80;
    server_name  _;

    root  /usr/share/nginx/html;

    location / {
        index index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth:8000/api/auth/;
    }

    location /api/orders/ {
        proxy_pass http://orders:8000/api/orders/;
    }
}